apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: omsagent
  namespace: kuberneteth
spec:
  template:
    metadata:
      labels:
        app: omsagent
    spec:
      containers:
      - env:
        - name: WSID
          value: 5a228ac6-eca0-4cef-810c-2506ddae510f
        - name: KEY
          value: baequtGePoKWGIBozvMBg0QjbPtoWx0RxDi/mrsXtOIsKUDophqqdsSym2OtQFGMiIG+jJqH5DRn0GyJB25CBQ==
        image: microsoft/oms
        name: omsagent
        ports:
        - containerPort: 25225
          protocol: TCP
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock