---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: truffle
  namespace: kuberneteth
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: truffle
    spec:
      containers:
      - name: truffle
        image: shanepeckham/truffle
